#       Retail Store Sales Analysis

This notebook provides an analysis of retail store sales data, focusing on various aspects such as revenue by payment method, total spent , product categories, discounts provided and the distribution of numerical features. 
The analysis aims to uncover insights that can help improve business strategies and customer satisfaction.

##  project workflow

1. project overview
2. Business questions
3. Data understanding
4. Data quality assessment

## 1. Project Overview  

    The retail store sales analysis project aims to analyze sales data from a retail store to gain insights into customer behavior, product performance, and overall business performance. The project will involve data cleaning, exploration, and visualization to identify trends and patterns in the sales data. The ultimate goal is to provide actionable recommendations to improve sales and customer satisfaction.

## 2. Business questions:

#### Sales and Revenue Analysis:
1. What is the total revenue generated?
2. How does revenue change over time (monthly, quarterly, yearly)?
3. Which categories contribute the most to revenue?
4. Which items (products) generate the most revenue?

#### Customer Behavior:
5. which customer generates the most revenue?

#### Payment Methods:
6. which payment methods contribute the most to revenue?
7. What are the most popular payment methods used by customers?

#### Discounts :
8. Do customers who received discounts spend more than those who did not receive discounts?
9. Is there a difference between the weekday and weekend sales in discounted and non-discounted transactions?

#### Relationships and Correlations:
10. Are there any correlations between numerical features (e.g., total spent, quantity, discount)?

# 3. Data Understanding

 ### 3.1 importing libraries

In [70]:
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as st

### 3.2 loading the dataset

In [71]:
pd.reset_option('display.max_rows')

In [72]:
df = pd.read_csv("retail_store_sales.csv")
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

### 3.3 Dataset Description

This dataset contains records of sales transactions from a retail store. Each row represents one transaction made by a customer.




| Column               | Description                                                   |
| -------------------- | ------------------------------------------------------------- |
| **Transaction ID**   | Unique identification number for each transaction.            |
| **Customer ID**      | Identification code of the customer who made the transaction. |
| **Category**         | General category of the purchased product.                    |
| **Item**             | Name of the specific purchased product.                       |
| **Price Per Unit**   | Price of one unit of the purchased product.                   |
| **Quantity**         | Number of units purchased in the transaction.                 |
| **Total Spent**      | Total monetary amount associated with the transaction.        |
| **Payment Method**   | Method used to pay for the transaction.                       |
| **Location**         | Location or sales channel where the transaction was made.     |
| **Transaction Date** | Date when the transaction occurred.                           |
| **Discount Applied** | Indicates whether a discount was applied to the transaction.  |

# 4 . Data Quality Assessment

In [73]:
# To view the first 5 rows 

df.head(5)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [74]:
print(f'The number of rows in the DataFrame is {df.shape[0]}')
print(f'The number of columns in the DataFrame is {df.shape[1]}')

The number of rows in the DataFrame is 12575
The number of columns in the DataFrame is 11

 ###   4.1  Check Data Types :

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

### 4.2 Check Duplicates

In [76]:
df.duplicated().sum()

np.int64(0)

### 4.3 Check for Missing Values

In [77]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [78]:
df.isnull().mean().round(2)*100

Transaction ID       0.0
Customer ID          0.0
Category             0.0
Item                10.0
Price Per Unit       5.0
Quantity             5.0
Total Spent          5.0
Payment Method       0.0
Location             0.0
Transaction Date     0.0
Discount Applied    33.0
dtype: float64

### 4.4 Check for Outliers for Numerical columns

In [79]:
for col in df.select_dtypes(include='number').columns:
    fig= px.box(data_frame=df,
                x= col,
                title= f'Box plot for {col}',
                color_discrete_sequence= ["#5D8BE7"])
    fig.show()

### 4.5 Check Summary statistics for Numerical columns

In [80]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

### 4.6 Check Summary statistics for Categorical columns

In [81]:
df.describe(include='object')

,Transaction ID,Customer ID,Category,Item,Payment Method,Location,Transaction Date,Discount Applied
count,12575,12575,12575,11362,12575,12575,12575,8376
unique,12575,25,8,200,3,2,1114,2
top,TXN_6867343,CUST_05,Electric household essentials,Item_2_BEV,Cash,Online,2022-05-30,True
freq,1,544,1591,126,4310,6354,26,4219

#  5. Data Cleaning

### 5.1 convart the data column to appropriate data type

In [82]:
# convert the transaction_date column to datetime form

df['Transaction Date']= pd.to_datetime(df['Transaction Date'])
df['Transaction Date']

0       2024-04-08
1       2023-07-23
2       2022-10-05
3       2022-05-07
4       2022-10-02
           ...
12570   2023-09-03
12571   2022-08-12
12572   2024-08-24
12573   2023-12-30
12574   2022-08-06
Name: Transaction Date, Length: 12575, dtype: datetime64[ns]

### 5.2    fill missing values in the dataset

In [83]:
1 # Price (Total_spent/ Quantity )

df['Price Per Unit'] =df['Price Per Unit'].fillna(df['Total Spent']/df['Quantity'])
df['Price Per Unit'] .isnull().sum()

np.int64(0)

In [84]:
2 # Quantity (Total_spent / price) wrong

# df['Quantity'] =df['Quantity'].fillna(df['Total Spent']/df['Price Per Unit'])
# df['Quantity'].isnull().sum()

2

In [85]:
2 # Quantity 
median_Quantity = df['Quantity'].median().round(2)
df['Quantity']=df['Quantity'].fillna(median_Quantity)

In [86]:
3 # Total Spent 
df['Total Spent'] =df['Total Spent'].fillna(df['Price Per Unit'] * df['Quantity'])

In [87]:
4 # Discount Applied fill by Unknown(no diff between them)
df['Discount Applied']= df['Discount Applied'].fillna('UnKnown')

In [88]:
5 # Item 
item_mapping = (
    df.dropna(subset=["Item", "Category", "Price Per Unit"])
    .groupby(["Category", "Price Per Unit"])["Item"]
    .first()
)


df["mapped_item"] = df.set_index(["Category", "Price Per Unit"]).index.map(
    item_mapping
)
df["Item"] = df["Item"].fillna(df["mapped_item"])


df.drop(columns=["mapped_item"], inplace=True)  


print("Done")

Done

In [89]:
# To check Again
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

### 5.3 Handle outliers in Total Spent column

In [90]:
# Detect indices outliers 
from datasist.structdata import detect_outliers
outlier_indices= detect_outliers(data= df ,n = 0,features=['Total Spent'])
outlier_indices

[27,
 133,
 339,
 869,
 1060,
 1088,
 1468,
 1505,
 1568,
 1950,
 1983,
 2153,
 2180,
 2182,
 2540,
 2658,
 3036,
 3094,
 3778,
 4526,
 4780,
 5364,
 5745,
 5756,
 5819,
 5969,
 6174,
 6374,
 6611,
 6785,
 7272,
 7372,
 7520,
 7716,
 7769,
 8076,
 8508,
 8596,
 8611,
 8845,
 8852,
 9214,
 9378,
 9620,
 9760,
 9884,
 9963,
 10103,
 10884,
 11093,
 11608,
 11610,
 11662,
 11670,
 12176,
 12189,
 12192,
 12209,
 12542,
 12557]

In [91]:
# HOW MANY OUTLIERS IN TOTAL SPENT COLUMN
len(outlier_indices)

60

In [92]:
# HANDLE OUTLIERS (This is normal data it's not a mistake so we will not delete  and we will not replace it with mean or median because it will affect the data distribution)
df[df['Total Spent'] > 400]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
27,TXN_1599706,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2024-03-24,True
133,TXN_2953434,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2023-08-10,UnKnown
339,TXN_4374445,CUST_12,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2024-10-17,UnKnown
869,TXN_1814138,CUST_06,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2024-11-16,UnKnown
1060,TXN_3710081,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2023-08-12,UnKnown
1088,TXN_1273334,CUST_22,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2022-11-04,True
1468,TXN_1938135,CUST_17,Butchers,Item_25_BUT,41.0,10.0,410.0,Digital Wallet,In-store,2023-12-20,True
1505,TXN_8520397,CUST_12,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Credit Card,Online,2024-03-27,True
1568,TXN_8048041,CUST_14,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2023-12-25,True
1950,TXN_1860120,CUST_01,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2022-01-19,True
1983,TXN_6924479,CUST_21,Patisserie,Item_25_PAT,41.0,10.0,410.0,Credit Card,Online,2022-06-11,UnKnown
2153,TXN_5338814,CUST_06,Milk Products,Item_25_MILK,41.0,10.0,410.0,Digital Wallet,Online,2023-03-13,False
2180,TXN_1172555,CUST_08,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,In-store,2023-04-01,True
2182,TXN_4047143,CUST_16,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,Online,2024-04-19,UnKnown
2540,TXN_2208547,CUST_05,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,Online,2022-02-23,True
2658,TXN_1227978,CUST_03,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2024-01-17,UnKnown
3036,TXN_2624160,CUST_16,Butchers,Item_25_BUT,41.0,10.0,410.0,Digital Wallet,Online,2022-06-19,True
3094,TXN_7177583,CUST_10,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,In-store,2024-08-31,False
3778,TXN_7898457,CUST_16,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,Online,2022-05-11,UnKnown
4526,TXN_3142066,CUST_24,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,Online,2024-07-17,UnKnown
4780,TXN_3465682,CUST_12,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2024-07-23,False
5364,TXN_8384530,CUST_02,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Credit Card,In-store,2023-12-25,False
5745,TXN_3855536,CUST_04,Computers and electric accessories,Item_25_CEA,41.0,10.0,410.0,Credit Card,In-store,2024-09-27,True
5756,TXN_4286472,CUST_12,Computers and electric accessories,Item_25_CEA,41.0,10.0,410.0,Credit Card,In-store,2022-06-10,UnKnown
5819,TXN_4456347,CUST_16,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,Online,2022-09-11,True
5969,TXN_2058333,CUST_25,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2023-01-17,UnKnown
6174,TXN_4428473,CUST_04,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,In-store,2022-07-28,True
6374,TXN_6219786,CUST_08,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2022-09-05,UnKnown
6611,TXN_7056530,CUST_09,Food,Item_25_FOOD,41.0,10.0,410.0,Credit Card,Online,2022-08-15,UnKnown
6785,TXN_6513125,CUST_14,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,Online,2023-05-20,False
7272,TXN_4858882,CUST_19,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2023-12-20,True
7372,TXN_8830035,CUST_17,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2022-07-05,True
7520,TXN_9553259,CUST_20,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,In-store,2023-05-01,UnKnown
7716,TXN_9628331,CUST_04,Food,Item_25_FOOD,41.0,10.0,410.0,Credit Card,Online,2022-09-03,UnKnown
7769,TXN_8688342,CUST_12,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2024-04-20,True
8076,TXN_3858239,CUST_23,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,In-store,2022-09-08,True
8508,TXN_4771109,CUST_21,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,In-store,2022-07-03,True
8596,TXN_2288041,CUST_24,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,In-store,2023-09-02,False
8611,TXN_3342443,CUST_08,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2023-10-03,True
8845,TXN_4208189,CUST_23,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,In-store,2022-06-07,False
8852,TXN_9745509,CUST_01,Patisserie,Item_25_PAT,41.0,10.0,410.0,Digital Wallet,In-store,2023-08-24,False
9214,TXN_2971834,CUST_11,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,Online,2022-08-29,True
9378,TXN_8837607,CUST_15,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,Online,2022-11-05,UnKnown
9620,TXN_2386101,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2025-01-04,True
9760,TXN_7254589,CUST_03,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,Online,2022-09-24,False
9884,TXN_8716794,CUST_13,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,Online,2024-05-29,False
9963,TXN_6651911,CUST_22,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2022-01-28,UnKnown
10103,TXN_1654267,CUST_03,Milk Products,Item_25_MILK,41.0,10.0,410.0,Cash,Online,2024-03-23,False
10884,TXN_5286547,CUST_16,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2023-02-16,False
11093,TXN_5710989,CUST_21,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2023-08-13,True
11608,TXN_7169895,CUST_07,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,In-store,2022-05-11,UnKnown
11610,TXN_6812555,CUST_02,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,In-store,2024-01-24,True
11662,TXN_5870737,CUST_17,Computers and electric accessories,Item_25_CEA,41.0,10.0,410.0,Credit Card,Online,2024-12-24,False
11670,TXN_9777368,CUST_01,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2023-10-10,True
12176,TXN_5150834,CUST_13,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2022-02-24,True
12189,TXN_9791556,CUST_18,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2024-01-27,False
12192,TXN_1657130,CUST_16,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,In-store,2022-03-02,UnKnown
12209,TXN_1113295,CUST_11,Milk Products,Item_25_MILK,41.0,10.0,410.0,Digital Wallet,Online,2022-08-23,False
12542,TXN_7484072,CUST_02,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2024-12-31,False
12557,TXN_7239201,CUST_24,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2024-05-01,False

# 6. In depth check for categorical columns

In [93]:
Catg_Cols = df.select_dtypes(include='object').columns


for col in Catg_Cols:
    print( col)
    print(df[col].nunique())
    print(df[col].unique())
    print('_' *100)

Transaction ID
12575
['TXN_6867343' 'TXN_3731986' 'TXN_9303719' ... 'TXN_5306010' 'TXN_5167298'
 'TXN_2407494']
____________________________________________________________________________________________________
Customer ID
25
['CUST_09' 'CUST_22' 'CUST_02' 'CUST_06' 'CUST_05' 'CUST_07' 'CUST_21'
 'CUST_23' 'CUST_25' 'CUST_14' 'CUST_15' 'CUST_17' 'CUST_01' 'CUST_10'
 'CUST_04' 'CUST_13' 'CUST_18' 'CUST_08' 'CUST_20' 'CUST_12' 'CUST_11'
 'CUST_19' 'CUST_16' 'CUST_24' 'CUST_03']
____________________________________________________________________________________________________
Category
8
['Patisserie' 'Milk Products' 'Butchers' 'Beverages' 'Food' 'Furniture'
 'Electric household essentials' 'Computers and electric accessories']
____________________________________________________________________________________________________
Item
200
['Item_10_PAT' 'Item_17_MILK' 'Item_12_BUT' 'Item_16_BEV' 'Item_6_FOOD'
 'Item_11_PAT' 'Item_1_FOOD' 'Item_20_FUR' 'Item_16_FUR' 'Item_22_BUT'
 'Item_3_BUT' 'Item_2_MILK' 'Item_2_FOOD' 'Item_24_PAT' 'Item_16_MILK'
 'Item_14_BEV' 'Item_17_PAT' 'Item_13_EHE' 'Item_21_FUR' 'Item_7_BEV'
 'Item_21_MILK' 'Item_4_EHE' 'Item_10_FOOD' 'Item_14_FUR' 'Item_24_FUR'
 'Item_20_BUT' 'Item_25_FUR' 'Item_14_FOOD' 'Item_22_PAT' 'Item_11_FOOD'
 'Item_6_PAT' 'Item_21_EHE' 'Item_13_PAT' 'Item_25_BEV' 'Item_23_FOOD'
 'Item_10_FUR' 'Item_11_BEV' 'Item_23_BUT' 'Item_22_BEV' 'Item_10_EHE'
 'Item_24_BUT' 'Item_8_BEV' 'Item_3_FOOD' 'Item_12_FOOD' 'Item_16_CEA'
 'Item_16_BUT' 'Item_5_CEA' 'Item_19_MILK' 'Item_23_FUR' 'Item_7_FUR'
 'Item_15_CEA' 'Item_6_MILK' 'Item_24_CEA' 'Item_22_CEA' 'Item_22_FOOD'
 'Item_2_BUT' 'Item_14_PAT' 'Item_12_PAT' 'Item_18_FOOD' 'Item_1_PAT'
 'Item_4_BEV' 'Item_22_FUR' 'Item_7_PAT' 'Item_20_CEA' 'Item_20_FOOD'
 'Item_11_FUR' 'Item_8_PAT' 'Item_25_PAT' 'Item_7_FOOD' 'Item_8_MILK'
 'Item_4_FOOD' 'Item_4_PAT' 'Item_4_MILK' 'Item_7_CEA' 'Item_6_EHE'
 'Item_21_BUT' 'Item_16_PAT' 'Item_25_CEA' 'Item_8_BUT' 'Item_10_CEA'
 'Item_5_FUR' 'Item_9_FOOD' 'Item_11_CEA' 'Item_21_CEA' 'Item_24_BEV'
 'Item_8_CEA' 'Item_8_EHE' 'Item_23_MILK' 'Item_23_BEV' 'Item_19_BEV'
 'Item_20_BEV' 'Item_24_FOOD' 'Item_6_BEV' 'Item_1_MILK' 'Item_24_MILK'
 'Item_2_CEA' 'Item_18_BUT' 'Item_1_FUR' 'Item_3_MILK' 'Item_11_MILK'
 'Item_13_CEA' 'Item_6_CEA' 'Item_2_FUR' 'Item_21_BEV' 'Item_8_FUR'
 'Item_13_BUT' 'Item_2_BEV' 'Item_7_BUT' 'Item_7_EHE' 'Item_14_CEA'
 'Item_19_EHE' 'Item_18_CEA' 'Item_17_FUR' 'Item_15_MILK' 'Item_20_EHE'
 'Item_16_EHE' 'Item_23_EHE' 'Item_1_EHE' 'Item_19_CEA' 'Item_25_FOOD'
 'Item_12_EHE' 'Item_22_EHE' 'Item_17_EHE' 'Item_25_BUT' 'Item_4_CEA'
 'Item_1_BUT' 'Item_12_BEV' 'Item_5_FOOD' 'Item_25_EHE' 'Item_9_CEA'
 'Item_6_FUR' 'Item_1_CEA' 'Item_5_MILK' 'Item_15_FUR' 'Item_15_PAT'
 'Item_3_BEV' 'Item_5_EHE' 'Item_1_BEV' 'Item_17_BUT' 'Item_20_MILK'
 'Item_13_FOOD' 'Item_11_EHE' 'Item_9_MILK' 'Item_17_FOOD' 'Item_20_PAT'
 'Item_9_PAT' 'Item_10_BEV' 'Item_17_CEA' 'Item_13_MILK' 'Item_5_BUT'
 'Item_22_MILK' 'Item_4_FUR' 'Item_15_EHE' 'Item_17_BEV' 'Item_19_PAT'
 'Item_2_PAT' 'Item_14_BUT' 'Item_6_BUT' 'Item_9_FUR' 'Item_12_CEA'
 'Item_5_PAT' 'Item_15_FOOD' 'Item_18_MILK' 'Item_14_MILK' 'Item_12_FUR'
 'Item_18_BEV' 'Item_23_CEA' 'Item_24_EHE' 'Item_2_EHE' 'Item_23_PAT'
 'Item_8_FOOD' 'Item_15_BEV' 'Item_9_EHE' 'Item_11_BUT' 'Item_18_EHE'
 'Item_3_FUR' 'Item_19_BUT' 'Item_3_PAT' 'Item_3_CEA' 'Item_19_FUR'
 'Item_7_MILK' 'Item_9_BEV' 'Item_10_BUT' 'Item_14_EHE' 'Item_18_FUR'
 'Item_25_MILK' 'Item_4_BUT' 'Item_15_BUT' 'Item_21_PAT' 'Item_21_FOOD'
 'Item_13_BEV' 'Item_5_BEV' 'Item_13_FUR' 'Item_18_PAT' 'Item_12_MILK'
 'Item_10_MILK' 'Item_16_FOOD' 'Item_19_FOOD' 'Item_3_EHE' 'Item_9_BUT']
____________________________________________________________________________________________________
Payment Method
3
['Digital Wallet' 'Credit Card' 'Cash']
____________________________________________________________________________________________________
Location
2
['Online' 'In-store']
____________________________________________________________________________________________________
Discount Applied
3
[True False 'UnKnown']
____________________________________________________________________________________________________

# 7.In depth check for Numerical columns

In [94]:
df.describe(include='number').round(2)

       Price Per Unit  Quantity  Total Spent
count        12575.00  12575.00     12575.00
mean            23.37      5.56       130.21
std             10.75      2.79        93.58
min              5.00      1.00         5.00
25%             14.00      3.00        52.00
50%             23.00      6.00       110.00
75%             33.50      8.00       192.00
max             41.00     10.00       410.00

# 8.Feature Engineering

### - Extract year, month, day from transaction date

In [95]:
# Create year column
df['Year']=df['Transaction Date'].dt.year
df['Year']

0        2024
1        2023
2        2022
3        2022
4        2022
         ...
12570    2023
12571    2022
12572    2024
12573    2023
12574    2022
Name: Year, Length: 12575, dtype: int32

In [96]:
# Create month_name column
df['Month']=df['Transaction Date'].dt.month_name()
df['Month']

0            April
1             July
2          October
3              May
4          October
           ...
12570    September
12571       August
12572       August
12573     December
12574       August
Name: Month, Length: 12575, dtype: object

In [97]:
# Create day_name column

df['Day']=df['Transaction Date'].dt.day_name()
df['Day']

0           Monday
1           Sunday
2        Wednesday
3         Saturday
4           Sunday
           ...
12570       Sunday
12571       Friday
12572     Saturday
12573     Saturday
12574     Saturday
Name: Day, Length: 12575, dtype: object

In [98]:
# Extract weekday and weekend

def day_category(x):
    if x in ('Saturday','Sunday'):
        return 'weekend'
    else:
        return 'weekday'

df['Day_type'] = df['Day'].apply(day_category)
df['Day_type']

0        weekday
1        weekend
2        weekday
3        weekend
4        weekend
          ...
12570    weekend
12571    weekday
12572    weekend
12573    weekend
12574    weekend
Name: Day_type, Length: 12575, dtype: object

#  9. Exploratory Data Analysis (EDA)

## 1- Univariate  Analysis

### 1.1 Numerical data

In [99]:
# For Numerical

num_cols = df.select_dtypes(include='number').columns

for col in num_cols:
    fig= px.histogram(data_frame=df,
                      x= col,
                      color_discrete_sequence=["#569DD4"],
                      title= f'Distribution of {col}'
                      )
    fig.show()

### 1.2   Categorical data

In [100]:
 # Category col

Cat_freq = df['Category'].value_counts().sort_values(ascending=False).reset_index()
Cat_freq


fig= px.bar(data_frame=Cat_freq,
            x= 'Category',
            y= 'count',
            text_auto=True,
            title= 'Category_Frequency',
            color_discrete_sequence= ["#569DD4"]
)

fig.show()

In [101]:
# Location Col

Location_Per = df['Location'].value_counts().sort_values(ascending=False).reset_index()
Location_Per


fig= px.pie(data_frame=Location_Per,
            names= 'Location',
            values= 'count',
            title= 'Location_Percentage',
            color_discrete_sequence= ["#569DD4"],
            hole=0.5
)

fig.show()

In [102]:
#  Payment Method Col

Payment_Method_Per = df['Payment Method'].value_counts().sort_values(ascending=False).reset_index()
Payment_Method_Per


fig= px.pie(data_frame= Payment_Method_Per,
            names= 'Payment Method',
            values= 'count',
            title= 'Payment_Method_Percentage',
            color_discrete_sequence= ["#569DD4"],
            hole=0.5
)

fig.show()

In [103]:
df.head(2)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Year,Month,Day,Day_type
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,2024,April,Monday,weekday
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,2023,July,Sunday,weekend

# 2- Bivariate Analysis

In [104]:
## Relations between variables

In [105]:
## Quantity  Vs  Total Spent  (num * num )

fig = px.scatter (data_frame= df,
           x= 'Quantity',
           y= 'Total Spent',
           title='Quantity Vs  Total Spent ',
           color_continuous_scale='RdBu')

fig.show()

In [106]:
## payment-method Vs location (cat * cat )

fig = px.histogram(data_frame= df,
           x= 'Payment Method',
           color= 'Location',
           barmode ='group',
           title='payment method Vs location',
           text_auto=True,
            color_discrete_sequence= ["#569DD4","#3D0B03"]
          
           )

fig.update_yaxes(title_text= 'num of transactions') 
fig.update_traces( textposition='outside')
fig.update_yaxes(showticklabels=False)
fig.update_layout(margin=dict(t=50))    

fig.show()

# 3.Multivariate Analysis

In [107]:
# Crrelation between numeric variables
corr_df = df.corr(numeric_only= True).round(2)
corr_df

                Price Per Unit  Quantity  Total Spent  Year
Price Per Unit            1.00      0.01         0.64  0.01
Quantity                  0.01      1.00         0.70 -0.01
Total Spent               0.64      0.70         1.00 -0.00
Year                      0.01     -0.01        -0.00  1.00

In [108]:
fig= px.imshow(corr_df, 
               text_auto= True,
               color_continuous_scale='RdBu',
               title='Correlation matrix Heatmap')

fig.show()

# 10.Business Analysis

 ## 10-1 KPIs

In [109]:
# Total Revenue 
Total_Revenue = df['Total Spent'].sum()
Total_Revenue

np.float64(1637367.0)

In [110]:
# Tottal Quantity Sold
Total_Quantity_Sold = df['Quantity'].sum()
Total_Quantity_Sold

np.float64(69900.0)

In [111]:
# number of unique customers    
Unique_Customers = df['Customer ID'].nunique()
Unique_Customers

25

In [112]:
# number of transactions
Total_Transactions = df['Transaction ID'].count()
Total_Transactions

np.int64(12575)

## 10-2 Sales performane

1-How does the revenue trend over time?

In [113]:
df_sorted = df.sort_values(by='Transaction Date', ascending=True)

In [114]:
# Yearly Revenue

Revenue_by_Year = df_sorted.groupby('Year')['Total Spent'].sum().reset_index()
Revenue_by_Year

   Year  Total Spent
0  2022     540602.5
1  2023     515501.0
2  2024     554296.0
3  2025      26967.5

In [115]:
fig= px.bar(data_frame= Revenue_by_Year,
         x= 'Year',
         y= 'Total Spent',
         title= 'Revenue Trend Over Time',
         color_discrete_sequence=["#569DD4"],
         text_auto=True
        )


fig.update_traces(texttemplate='%{y:.0f}', textposition='outside')
fig.update_layout (margin=dict(t=50))
fig.update_xaxes(type='category')
fig.update_yaxes(title_text='Total Revenue',
                 showticklabels=False,
                )

fig.show()

In [116]:
# Monthly Revenue 

Revenue_by_Month = df_sorted.groupby('Month')['Total Spent'].sum().reset_index()
Revenue_by_Month

        Month  Total Spent
0       April     132164.5
1      August     129656.5
2    December     137605.5
3    February     127662.0
4     January     183637.0
5        July     138364.0
6        June     135906.0
7       March     129844.0
8         May     132076.5
9    November     130101.5
10    October     125827.5
11  September     134522.0

In [117]:
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

Revenue_by_Month['Month'] = pd.Categorical(Revenue_by_Month['Month'], categories=month_order, ordered=True)
Revenue_by_Month = Revenue_by_Month.sort_values('Month')


fig= px.line(data_frame = Revenue_by_Month,
         x= 'Month',
         y= 'Total Spent',
         title= 'Revenue Trend Over Months',
         color_discrete_sequence=["#569DD4"],
         category_orders= {'Month': month_order},
         markers=True
         
        
         )


fig.update_yaxes(title_text='',showticklabels=True)
fig.update_layout(margin=dict(t=50))
fig.show()

### 2-Which product category has the highest revenue?

In [118]:
Revenue_by_Category = df.groupby('Category')['Total Spent'].sum().sort_values(ascending=False).reset_index()
Revenue_by_Category

                             Category  Total Spent
0                            Butchers     218153.0
1       Electric household essentials     215297.5
2                           Beverages     206854.5
3                           Furniture     205390.0
4                                Food     205225.0
5  Computers and electric accessories     202023.5
6                          Patisserie     194531.5
7                       Milk Products     189892.0

In [119]:
fig = px.bar(data_frame=Revenue_by_Category,
             x='Category',
             y='Total Spent',
             title='Revenue by Category',
             text_auto=True,
             color_discrete_sequence=["#569DD4"])

fig.update_traces(texttemplate='%{y:.0f}', textposition='outside')
fig.update_yaxes(title_text='Total Revenue',showticklabels=False)
fig.update_layout(margin=dict(t=50))

fig.show()

In [ ]:
# what are the top 5 selling items in the Butchers Category , and what is their percentage contribution to the total revenue ?
Top_5_Butchers= df[df['Category']== 'Butchers'].groupby('Item')['Total Spent'].sum().reset_index().sort_values(by='Total Spent',ascending=False)

### 3- Which products are the biggest revenue contributors? Top(10)

In [120]:
Revenue_by_products = df.groupby('Item')['Total Spent'].sum().sort_values(ascending=False).reset_index().head(10)
Revenue_by_products

           Item  Total Spent
0   Item_25_FUR      27101.0
1   Item_25_EHE      26732.0
2   Item_24_FUR      23739.5
3   Item_25_BUT      23657.0
4  Item_25_FOOD      22755.0
5   Item_22_BUT      22557.0
6   Item_23_BUT      22192.0
7  Item_19_MILK      21600.0
8   Item_23_EHE      21546.0
9   Item_19_CEA      21408.0

In [121]:
fig = px.bar(data_frame= Revenue_by_products,
             x='Item',
             y='Total Spent',
             title='Revenue by products',
             text_auto=True,
             color_discrete_sequence=["#569DD4"])

fig.update_traces(texttemplate='%{y:.0f}', textposition='outside')
fig.update_yaxes(title_text='Total Revenue',showticklabels=False)
fig.update_layout(margin=dict(t=50))


fig.show()

4- There is difference in revenue between weekdays and weekends?

In [122]:
week_day = df.groupby('Day_type')['Total Spent'].mean().sort_values(ascending=False).reset_index()
week_day

  Day_type  Total Spent
0  weekend   131.294330
1  weekday   129.772753

In [123]:
fig = px.bar(data_frame= week_day,
             x='Day_type',
             y='Total Spent',
             title='Revenue by Day Type',
             text_auto=True,
             labels={'Day_type': '', 'Total Spent': ''},
             color_discrete_sequence=["#569DD4"])

fig.update_traces( textposition='outside')
fig.update_yaxes(showticklabels=False)
fig.update_layout(margin=dict(t=50))

fig.show()

# 10-3 Customer Analysis

1- Which customers generate the most revenue? Top(10)

In [124]:
customer_revenue = df.groupby('Customer ID')['Total Spent'].sum().reset_index().sort_values(by='Total Spent', ascending=False).head(10)
customer_revenue

   Customer ID  Total Spent
23     CUST_24      71890.0
7      CUST_08      70822.5
4      CUST_05      70631.5
12     CUST_13      68904.0
22     CUST_23      68554.0
15     CUST_16      68225.5
9      CUST_10      66419.5
21     CUST_22      65980.5
14     CUST_15      65601.5
20     CUST_21      65366.0

In [125]:
fig = px.bar(data_frame= customer_revenue,
             x='Customer ID',
             y='Total Spent',
             title='Revenue by Customer ',
             text_auto=True,
             color_discrete_sequence=["#569DD4"])

fig.update_traces(texttemplate='%{y:.0f}', textposition='outside')
fig.update_yaxes(title_text='Total Revenue',showticklabels=False)
fig.update_layout(margin=dict(t=50))


fig.show()

2- Dose customers who received discounts spend more than those who did not receive discounts?

In [126]:
Discount_Vs_NonDiscount =df.groupby(['Discount Applied'])['Total Spent'].mean().sort_values(ascending=False).reset_index()
Discount_Vs_NonDiscount

  Discount Applied  Total Spent
0             True   130.972861
1            False   130.796728
2          UnKnown   128.856990

In [127]:
fig= px.bar(data_frame= Discount_Vs_NonDiscount,
            x= 'Discount Applied',
            y= 'Total Spent',
            title= 'Discount vs Non-Discount Spending',
            color_discrete_sequence=["#569DD4"],
            text_auto=True,
            labels={'Total Spent': 'Total Revenue', 'Discount Applied': 'Discount Applied'},
            

)  
fig.update_traces( textposition='outside')
fig.update_yaxes(showticklabels=False)
fig.update_layout(margin=dict(t=50))

fig.show()

3- Which customers make the most transactions?

In [128]:
customer_frequency = (
    df.groupby('Customer ID')['Transaction ID']
      .nunique()
      .reset_index(name='Transactions')
      .sort_values('Transactions', ascending=False)
      .head(10)
)
customer_frequency

   Customer ID  Transactions
4      CUST_05           544
23     CUST_24           543
12     CUST_13           534
7      CUST_08           533
8      CUST_09           519
14     CUST_15           519
15     CUST_16           515
22     CUST_23           513
0      CUST_01           507
19     CUST_20           507

In [129]:
fig = px.bar(data_frame= customer_frequency,
             x='Transactions',
             y='Customer ID',
             title='Top 10 Transaction by Customer ',
             text_auto=True,
             color_discrete_sequence=["#569DD4"])

fig.update_traces( textposition='outside')
fig.update_yaxes(title_text='Customer ID')
fig.update_layout(margin=dict(t=50))


fig.show()

In [130]:
df.head(2)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Year,Month,Day,Day_type
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,2024,April,Monday,weekday
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,2023,July,Sunday,weekend

# 10-4 Payment Method Analysis

1-which payment methods contribute the most to revenue?

In [131]:
Revenue_by_payment_method = df.groupby('Payment Method')['Total Spent'].sum().sort_values(ascending=False).reset_index()
Revenue_by_payment_method

   Payment Method  Total Spent
0            Cash     567275.0
1  Digital Wallet     535617.0
2     Credit Card     534475.0

In [132]:
fig= px.bar(data_frame= Revenue_by_payment_method,
            x= 'Payment Method',
            y= 'Total Spent',
            title= 'Revenue Contribution by Payment Method',
            color_discrete_sequence=["#569DD4"],
            text_auto=True,
            labels={'Total Spent': 'Total Revenue', 'Payment Method': 'Payment Method'},
            

)  
fig.update_traces( textposition='outside')
fig.update_yaxes(showticklabels=False)
fig.update_layout(margin=dict(t=50))

fig.show()

2- Which payment methods are used most frequently?

In [133]:
payment_usage = (
    df.groupby('Payment Method')['Transaction ID']
      .nunique()
      .reset_index(name='Transactions')
      .sort_values('Transactions', ascending=False)
)

payment_usage

   Payment Method  Transactions
0            Cash          4310
2  Digital Wallet          4144
1     Credit Card          4121

In [134]:
fig= px.bar(data_frame = payment_usage,
            x= 'Transactions',
            y= 'Payment Method',
            title= 'Payment Method Usage',
            color_discrete_sequence=["#569DD4"],
            text_auto=True,
                  

)  
fig.update_traces( textposition='outside')
fig.update_layout(margin=dict(t=50))

fig.show()

- Which location has the highest revenue?

In [135]:
Total_Spent_by_Location = df.groupby('Location')['Total Spent'].sum().sort_values(ascending=False).reset_index()
Total_Spent_by_Location

   Location  Total Spent
0    Online     831922.0
1  In-store     805445.0

In [136]:
fig= px.pie(data_frame= Total_Spent_by_Location,
            names= 'Location',
            values= 'Total Spent',
            title= 'Total Revenue by Location',
            color_discrete_sequence=["#569DD4"],
            hole=0.5
)  

fig.show()

# Key Insights

* **Total Revenue:** The dataset generated a total revenue of **$1,637,367**.

* **Highest-Revenue Category:** **Butchers** was the highest-revenue category, generating **$218,153**.

* **Sales Channel:** **Online sales** generated the highest revenue, with total revenue of **$831,922**.

* **Most Frequently Used Payment Method:** **Cash** was the most frequently used payment method, with **4,310 transactions**.

* **Highest-Value Customer:** **CUST_24** was the highest-value customer, contributing **$71,890** in revenue.

* **Weekend Performance:** Transactions during the **weekend** had the highest average spending, with an average transaction value of approximately **$131.29**.

* **Highest-Revenue Product:** **Item_25_FUR** was the highest-revenue product, generating **$27,101**.

# Recommendations

# 9. Business Recommendations

Based on the analysis and the identified sales and customer patterns, the following recommendations can be considered:

### 1. Focus on High-Performing Product Categories

The **Butchers** category generated the highest revenue at **$218,153**. The business should closely monitor inventory and demand for high-performing categories and consider prioritizing them in marketing and sales strategies.

### 2. Strengthen the Online Sales Channel

**Online sales generated $831,922**, making Online the strongest sales channel in terms of revenue. The business could explore opportunities to improve the online shopping experience and encourage further online purchases.

### 3. Retain High-Value Customers

**CUST_24** generated **$71,890**, indicating the importance of high-value customers. The business should identify and retain similar high-value customers through personalized offers, loyalty strategies, and targeted communication.

### 4. Monitor Cash Payment Usage

**Cash was the most frequently used payment method, with 4,310 transactions.** The business should continue supporting cash payments while monitoring whether digital payment methods are growing or generating higher-value transactions.

### 5. Investigate Weekend Purchasing Behavior

Weekend transactions had the highest **average transaction value**, at approximately **$131.29**. The business could investigate the reasons behind higher weekend spending and consider targeted weekend promotions or product bundles.

### 6. Prioritize High-Revenue Products

**Item_25_FUR** generated the highest product revenue at **$27,101**. The business should monitor its availability and demand and consider using similar high-performing products in promotional and merchandising strategies.

### 7. Use Data-Driven Decision Making

Future business decisions should consider multiple indicators—including revenue, transaction frequency, average transaction value, customer contribution, and sales channel performance—rather than relying on a single metric.

## Save Cleaned Dataframe

In [137]:
## Discount Applied has Unknown values and the parquet could not convert it 
df["Discount Applied"]= df["Discount Applied"].astype(str)

In [138]:
df.to_parquet("retail_store_sales_clean.parquet")